name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Vue App
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies safely
        run: npm install --legacy-peer-deps
        working-directory: web/Serverless-Microsservices-Web2

      - name: Build app with Vite
        run: npx vite build
        working-directory: web/Serverless-Microsservices-Web2

      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_GLACIER_00DF2D31E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Required for auto-deployment comments
          action: "upload"
          app_location: "web/Serverless-Microsservices-Web2"
          output_location: "dist"
